### ISSUE TITLE
coc_nvim_1.workspace.resolveRootFolder is not a function

### ISSUE THREAD

**Issue by xavicampa** [joenye/coc-cfn-lint#19]
This started appearing yesterday when opening CloudFormation templates. Unsure if the error and the warning are related, sorry if they are not.

`2022-02-23T09:07:21.221 INFO (pid:3755) [plugin] - coc.nvim initialized with node: v17.5.0 after 45ms
2022-02-23T09:07:27.094 WARN (pid:3755) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead.
    at new CfnLintEngine (/Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:181:51)
    at Object.<anonymous> (/Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:106:16)
2022-02-23T09:07:27.095 ERROR (pid:3755) [extensions] - Error on active extension coc-cfn-lint: coc_nvim_1.workspace.resolveRootFolder is not a function TypeError: coc_nvim_1.workspace.resolveRootFolder is not a function
    at CfnLintEngine.<anonymous> (/Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:190:62)
    at Generator.next (<anonymous>)
    at /Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:166:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:162:12)
    at CfnLintEngine.init (/Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:187:16)
    at Object.<anonymous> (/Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:129:22)
    at Generator.next (<anonymous>)
    at /Users/javi/.config/coc/extensions/node_modules/coc-cfn-lint/lib/index.js:99:71
    at new Promise (<anonymous>)`

nvim and coc versions:
`vim version: NVIM v0.6.1
node version: v17.5.0
coc.nvim version: 0.0.80-3e0c33eca4
coc.nvim directory: /Users/javi/.local/share/nvim/plugged/coc.nvim
term: alacritty
platform: darwin`

**Comment by ayersb** [comment]
I just ran into the same issue @xavicampa. It appears the `workspace.resolveRootFolder` used [here](https://github.com/joenye/coc-cfn-lint/blob/768880a745a1dc02d891badab61d56fc77d4e4df/src/engine.ts#L46) was deprecated and then removed in January. I found the [commit](https://github.com/neoclide/coc.nvim/commit/66cb2e9521db0990ad94c08e100ce95e8a406b9d) where it was taken out of coc

**Comment by joenye** [comment]
Thanks both for identifying the issue. Unfortunately, I don't use this plugin any more.

I'll gladly accept a PR to fix this.

**Comment by joenye** [comment]
Fixed in latest commit. Closing.
